apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-2-2
spec:
  selector:
    matchLabels:
      app: task-2-2
  template:
    metadata:
      labels:
        app: task-2-2
    spec:
      containers:
        - name: task-2-2
          image: kxingjing/task-processor:2.0
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 5001
          env:
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
---
apiVersion: v1
kind: Service
metadata:
  name: task-2-2
spec:
  type: NodePort
  selector:
    app: task-2-2
  ports:
    - port: 80
      targetPort: 5001
      nodePort: 30003
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: task-2-2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: task-2-2
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 85
