apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-1
spec:
  selector:
    matchLabels:
      app: task-1
  template:
    metadata:
      labels:
        app: task-1
    spec:
      containers:
        - name: task-1
          image: kxingjing/task-1:1.0
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
          env:
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
---
apiVersion: v1
kind: Service
metadata:
  name: task-1
spec:
  type: NodePort
  selector:
    app: task-1
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30001
